targets:
  $default:
    builders:
      source_gen|combining_builder:
        options:
          build_extensions:
            "^lib/src/shared/data/models/{{}}.dart": "lib/src/shared/data/generated/{{}}.g.dart"
