---
name: quran_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=3.4.0 <4.0.0'
dependencies:
  auto_route: ^9.2.2
  bloc: ^8.1.4
  collection: ^1.18.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  flutter_svg: ^2.0.10+1
  dio: ^5.7.0
  equatable: ^2.0.5
  scrollable_positioned_list: ^0.3.8
  shimmer: ^3.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^7.7.0
  json_annotation: ^4.9.0
  persistent_bottom_nav_bar: ^6.2.1
  pretty_dio_logger: ^1.4.0
  google_fonts: ^6.2.1

dev_dependencies:
  auto_route_generator: ^9.0.0
  build_runner: ^2.4.10
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/images/
